fix type error with collideTiles
src/libs/littlejs.d.ts:1883:9 - error TS2416: Property 'collideTiles' in type 'ParticleEmitter' is not assignable to the same property in base type 'EngineObject'.
  Type 'boolean' is not assignable to type 'number'.

1883         collideTiles: boolean;