fix some ts build errors and rebuild
fixes...

src/libs/littlejs.d.ts:800:27 - error TS2552: Cannot find name 'float'. Did you mean 'GLfloat'?
800         toString(digits?: float): string;

src/libs/littlejs.d.ts:1458:9 - error TS2416: Property 'play' in type 'Music' is not assignable to the same property in base type 'Sound'.
  Type '(volume?: number, loop?: boolean) => AudioBufferSourceNode' is not assignable to type '(pos?: Vector2, volume?: number, pitch?: number, randomnessScale?: number, loop?: boolean) => AudioBufferSourceNode'.
    Types of parameters 'volume' and 'pos' are incompatible.
      Type 'Vector2' is not assignable to type 'number'.
1458         play(volume?: number, loop?: boolean): AudioBufferSourceNode;

src/libs/littlejs.d.ts:1761:85 - error TS1016: A required parameter cannot follow an optional parameter.
1761         drawCanvas2D(pos: Vector2, size: Vector2, angle?: number, mirror?: boolean, drawFunction: Function): void;

src/libs/littlejs.d.ts:1863:9 - error TS2416: Property 'collideTiles' in type 'ParticleEmitter' is not assignable to the same property in base type 'EngineObject'.
  Type 'boolean' is not assignable to type 'number'.
1863         collideTiles: boolean;