fix typescript issue
src/libs/littlejs.d.ts:1761:85 - error TS1016: A required parameter cannot follow an optional parameter.
1761         drawCanvas2D(pos: Vector2, size: Vector2, angle?: number, mirror?: boolean, drawFunction: Function): void;